[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
kvm-bindings = "0.14.0"
kvm-ioctls = "0.24.0"
nix = {version = "0.30.1", features = ["ioctl"] }
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }
vm-device = { path = "crates/vm-device" }
