name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_BACKTRACE: 1
  RUST_STABLE: stable
  RUST_NIGHTLY: nightly-2025-10-12

defaults:
  run:
    shell: bash

jobs:
  build_x86_64:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - uses: Swatinem/rust-cache@v2
      - name: build
        run: cargo build --verbose

  build_aarch64:
    name: Build(AArch64)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_STABLE }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
      - uses: Swatinem/rust-cache@v2
      - name: Install cross
        uses: taiki-e/install-action@v2
        with:
          tool: cross
      - name: build(MacOS/hvp)
        run: cargo build --no-default-features --features hvp --verbose
      - name: Build(Linux/kvm)
        run: cross build --target aarch64-unknown-linux-gnu --verbose

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          components: clippy
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --all-targets

  udeps:
    name: Udeps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust ${{ env.RUST_NIGHTLY }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - name: udeps
        run: cargo udeps --all-targets
